### ISSUE TITLE
Update readme to also include installation of peer dependencies

### ISSUE THREAD

**Issue by mikheevm** [gnosis/safe-react-components#102]
We have some peer dependencies for the package:

https://github.com/gnosis/safe-react-components/blob/development/package.json#L73-L78

It's not clear that you have to install them until you run into a problem or casually browse through package.json

**Comment by katspaugh** [comment]
Updated the readme [here](https://github.com/gnosis/safe-react-components/pull/116/commits/0bff91318676dab92d780f24c4f54425e9823b6a).
