### ISSUE TITLE
Received `true` for a non-boolean attribute `compact`

### ISSUE THREAD

**Issue by fernandomg** [gnosis/safe-react-components#105]
![image](https://user-images.githubusercontent.com/3315606/110375333-9a460e00-8030-11eb-8300-59ee9a89e450.png)

This issue is related to the `Accordion` component.

For some reason, it interprets `compact` as a string prop, despite it's being declared as boolean?

**Comment by katspaugh** [comment]
`compact` is indeed a boolean, and it's passed as a boolean. It's just that it's assigned to an internal div as a DOM property. The same type of issue as #104.

**Comment by katspaugh** [comment]
A solution to both this and #104 would be to use [Transient props](https://styled-components.com/docs/api#transient-props).

In this case, passing `compact` as `$compact` to the `StyledAccordion`.
