### ISSUE TITLE
create IconText component.

### ISSUE THREAD

**Issue by nicosampler** [gnosis/safe-react-components#109]
I think we should create a component that renders an Icon and a text. 

- [x] It should be configurable to support icon + text and text + icon.
- [x] Add default spacing, if you find in the designs there can be more than one spacing, make it configurable through the theme. 
- [ ] Once merged, replace/remove the one in safe-react.

![image](https://user-images.githubusercontent.com/4376509/112830039-5f9c2800-9068-11eb-8021-e5e8b1ee4595.png)

**Comment by alongoni** [comment]
We have to improve the existing one:
https://components.gnosis-safe.io/?path=/docs/data-display-icon-text--sizes

**Comment by iamacook** [comment]
I spoke with @alongoni yesterday and this is seemingly no longer necessary as the code has changed in SR:

![image](https://user-images.githubusercontent.com/20442784/132315228-67985fb6-ee35-45aa-b21d-c6c08d0391af.png)

Maybe we can close this and rename the component in SR to something more relevant? @katspaugh
