### ISSUE TITLE
Create radio button

### ISSUE THREAD

**Issue by fernandomg** [gnosis/safe-react-components#22]
![image.png](https://images.zenhubusercontent.com/5d63d58a19b1c600016a9a89/eedac586-cc67-4fe3-bd79-e62506f7c2cf)

**Comment by iamacook** [comment]
We seemingly have a radio button component in SRC now? @katspaugh

![image](https://user-images.githubusercontent.com/20442784/132311087-b700da4c-9620-42bf-96d6-70f1c7ba459e.png)

**Comment by katspaugh** [comment]
Seems like it, @iamacook. Good catch! Let's close it then.
