### ISSUE TITLE
Create table component

### ISSUE THREAD

**Issue by fernandomg** [gnosis/safe-react-components#27]
![image.png](https://images.zenhubusercontent.com/5d63d58a19b1c600016a9a89/8030a966-5c1a-48f3-840b-aa0d59608348)

**Comment by mikheevm** [comment]
Why we can't just use table from material-ui? Table is something that we want to be highly customizable and this is only possible with crafting our own table from `TableCell`, `TableHeader` components from MUI

**Comment by mikheevm** [comment]
Creating a **Table** component (just table) that would allow the same level of customisation is a very hard task and I'm not sure if we want to spend time on this
