### ISSUE TITLE
Allow `Text` to be inline

### ISSUE THREAD

**Issue by fernandomg** [gnosis/safe-react-components#53]
Currently, `Text` is returning a `<p />` element. Some times we need to use it but in an _inline_ fashion.

So, maybe by adding an optional prop `isInline` can do the trick and return a `<span />` instead.

```typescript
<Text size="md" isInline /> // -> span
<Text size="md" /> // -> p
```

**Comment by nicosampler** [comment]
This feature was already implemented.
