### ISSUE TITLE
Rebuild Safe components library on Chakra UI

### ISSUE THREAD

**Issue by krzysu** [gnosis/safe-react-components#63]
I have some experience with components available in this repo and I always find them terrible to work with. It would be way better for everybody (also easier for you) if you rebuilt your design system on top of Chakra UI (https://chakra-ui.com/). With the next version of Chakra, it is even easier to define your theme (https://next.chakra-ui.com/docs/theming/customize-theme). Chakra gives you a massive library of components available out of the box. It provides great documentation. You could just provide a Gnosis Safe theme for Chakra as a simple solution or enhance the library with your custom components.

It's just a suggestion to make everybody happy and save unnecessary work and frustration. I worked with Chakra before and I want to recommend it.

**Comment by katspaugh** [comment]
Hi Kris,
Thanks for the feedback! Could you elaborate what makes the current system terrible to use?

**Comment by krzysu** [comment]
Hi, it was a long time ago, so I assume the status quo changed already. That time I worked on https://github.com/krzysu/safe-app-idle-v4 and I remember issues with the general composability of different components and lack of features I would expect from a component library. But now it's hard to say. Feel free to ignore/close this issue.

I found only one place now where I had to overwrite Safe UI defaults, maybe this can help https://github.com/krzysu/safe-app-idle-v4/blob/5b70fda92f4f661a2063e2f487c9aa544d782d3e/src/components/GlobalStyle.ts#L21

**Comment by katspaugh** [comment]
I see, so it's about composability & overriding our defaults. Fair point.

I'd say we'll close this particular issue for now. We'll definitely discuss how to improve those points. We've had similar feedback from other users. Not sure it's going to be a completely different framework but we'll see.

Thanks again! 👍
