### ISSUE TITLE
Add Breadcrumb component

### ISSUE THREAD

**Issue by alongoni** [gnosis/safe-react-components#78]
**Design reference:**
https://app.zeplin.io/project/5b83b4fa75f90943c86ed14f/screen/5dcd2226ea1de42333f7945f

**Icon + Main section**
https://app.zeplin.io/project/5b83b4fa75f90943c86ed14f/screen/5f5b8ca1d8db3d488a2b9710
![image](https://user-images.githubusercontent.com/622217/115869417-3d51bc00-a414-11eb-972a-f4123195f7f1.png)

**Icon + Main section + Sub section**
https://app.zeplin.io/project/5b83b4fa75f90943c86ed14f/screen/5f32488064c40451cd30e841
![image](https://user-images.githubusercontent.com/622217/115869342-1e532a00-a414-11eb-8030-a1a56efbac26.png)

**Icon + Main section + Counter**
https://app.zeplin.io/project/5b83b4fa75f90943c86ed14f/screen/5f5b904b0faf6c76b20961f3
![image](https://user-images.githubusercontent.com/622217/115869655-93266400-a414-11eb-9284-968b600a5e7e.png)

**Comment by nicosampler** [comment]
@alongoni can you add a link to the designs?
